filebeat.inputs:
- type: log
  enabled: false  # Inputs are disabled because the MySQL module handles log collection

# Modules configuration
filebeat.config.modules:
  path: /usr/share/filebeat/modules.d/*.yml
  reload.enabled: true
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~


output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}

setup.kibana:
  host: "kibana" 
  username: "elastic"  
  password: "${KIBANA_SYSTEM_PASSWORD}"
  ssl.verification_mode: none

setup.dashboards.enabled: true
